### PR TITLE
spanish translation

### PR DESCRIPTION
**Pull request by victorhck**
Hello!
I have created a spanish translation for this plasmoid.
BTW, I have all in spanish, but when I put the cursor above the moon image, I have a popup window and it's not translated:
http://susepaste.org/25876701
I miss something? I made something wrong?

Thanks for your time and effort.

### CODE REVIEW

**Comment by Koffeinfriedhof** [comment]
Hi!

Thanks for being interested in this small plasmoid :) I think you didn't do anything wrong, it is an issue with my Messages.sh not getting all lines that should be translated. (missing the lines in the java-script-files)

You can see this by grepping after "Waxing" or so, e.g.:
```
cd %gealachClone%/po
Messages.sh es
grep Waxing *.po
```
which will only output the existing files in french and german.

I'll have a look at it these days. As a workaround you could use the _"plasma_applet_org.koffeinfriedhof.gealach_fr.po"_ file as a template and save it as _"plasma_applet_org.koffeinfriedhof.gealach_es.po"_, applying (and copying) your changes to it.

I'm sorry for the circumstances I've made…

**Comment by victorhck** [comment]
Translated the missing messages, using the fr translation as template.

> I'm sorry for the circumstances I've made…

No problem! Thanks for your time, code and support! ;)

Happy hacking

**Comment by victorhck** [comment]
Now I get a mixed translation... :)
http://susepaste.org/62196551
I think that all the items are translated, don't know where is the text in english.

**Comment by Koffeinfriedhof** [comment]
Hey, sorry for the late reply. I will have a look at it this weekend and hope to fix this bug asap. Time is running fast these days :)

**Comment by Koffeinfriedhof** [comment]
Just made a workaround for it. It is working for me in arch now, but at least I have to write another implementation to have it properly done.

**Pull request merged**
